var COUNTRY = [
  {"name": "Norge", "mode":"active"},
  {"name": "USA"},
  {"name": "Danmark"},
  {"name": "Sverige"},
  {"name": "Djibouti"},
  {"name": "Uruguay"},
  {"name": "Swaziland"},
  {"name": "Usbekistan"},
  {"name": "Republikken Kongo"},
  {"name": "Brunei"},
  {"name": "Tokelau (NZ)"},
  {"name": "Malta"},
  {"name": "Jersey (Storbritannia)"},
  {"name": "Bahamas"},
  {"name": "Liberia"},
  {"name": "Brasil"},
  {"name": "Luxembourg"},
  {"name": "Antigua og Barbuda"},
  {"name": "Belize"},
  {"name": "Italia"},
  {"name": "Saint Lucia"},
  {"name": "Sierra Leone"},
  {"name": "Montenegro"},
  {"name": "Sør-Korea"},
  {"name": "Libya"},
  {"name": "Papua Ny-Guinea"},
  {"name": "Qatar"},
  {"name": "Kypros"},
  {"name": "Kroatia"},
  {"name": "Zambia"},
  {"name": "Frankrike"},
  {"name": "Puerto Rico"},
  {"name": "Mali"},
  {"name": "Aserbajdsjan"},
  {"name": "Litauen"},
  {"name": "Nepal"},
  {"name": "Chile"},
  {"name": "Kamerun"},
  {"name": "Dominica"},
  {"name": "Kirgisistan"},
  {"name": "Vatikanstaten"},
  {"name": "Kasakhstan"},
  {"name": "Maldivene"},
  {"name": "Christmasøya (Australia)"},
  {"name": "Israel"},
  {"name": "Kambodsja"},
  {"name": "Østerrike"},
  {"name": "Mosambik"},
  {"name": "Anguilla (Storbritannia)"},
  {"name": "Algerie"},
  {"name": "Thailand"},
  {"name": "Saint-Pierre og Miquelon (Frankrike)"},
  {"name": "Tunisia"},
  {"name": "Tsjad"},
  {"name": "De franske sørterritorier (Frankrike)"},
  {"name": "Isle of Man (Storbritannia)"},
  {"name": "Jordan"},
  {"name": "Irak"},
  {"name": "Tonga"},
  {"name": "Gambia"},
  {"name": "Bermuda (Storbritannia)"},
  {"name": "Norfolkøya (Australia)"},
  {"name": "Samoa"},
  {"name": "Forente Arabiske Emirater"},
  {"name": "Vanuatu"},
  {"name": "Guernsey (Storbritannia)"},
  {"name": "Mauritania"},
  {"name": "Island"},
  {"name": "Peru"},
  {"name": "Turks- og Caicosøyene (UK)"},
  {"name": "Trinidad og Tobago"},
  {"name": "Rwanda"},
  {"name": "England (Storbritannia)"},
  {"name": "Palau"},
  {"name": "Tuvalu"},
  {"name": "Myanmar"},
  {"name": "Barbados"},
  {"name": "Cook-øyene (New Zealand)"},
  {"name": "Belgia"},
  {"name": "Burundi"},
  {"name": "Ny-Caledonia (Frankrike)"},
  {"name": "Komorene"},
  {"name": "Niue (New Zealand)"},
  {"name": "Nederland"},
  {"name": "Curaçao (Nederland)"},
  {"name": "Nord-Korea"},
  {"name": "Cuba"},
  {"name": "Guyana"},
  {"name": "Armenia"},
  {"name": "Tyrkia"},
  {"name": "Laos"},
  {"name": "Filippinene"},
  {"name": "Mongolia"},
  {"name": "Argentina"},
  {"name": "Liberia"},
  {"name": "Marshalløyene"},
  {"name": "Egypt"},
  {"name": "Elfenbenskysten"},
  {"name": "Luxembourg"},
  {"name": "Sør-Afrika"},
  {"name": "Tanzania"},
  {"name": "Malawi"},
  {"name": "Sint Maarten (Nederland)"},
  {"name": "Saint Kitts og Nevis"},
  {"name": "De amerikanske jomfruøyene"},
  {"name": "Haiti"},
  {"name": "Bolivia"},
  {"name": "Albania"},
  {"name": "Benin"},
  {"name": "Kina"},
  {"name": "Gibraltar (Storbritannia)"},
  {"name": "Bulgaria"},
  {"name": "India"},
  {"name": "Monaco"},
  {"name": "Costa Rica"},
  {"name": "Sri Lanka"},
  {"name": "Syria"},
  {"name": "Sentralafrikanske Republikk"},
  {"name": "Jemen"},
  {"name": "Kuwait"},
  {"name": "Nepal"},
  {"name": "Ghana"},
  {"name": "Singapore"},
  {"name": "Madagaskar"},
  {"name": "Estland"},
  {"name": "Nigeria"},
  {"name": "Fiji"},
  {"name": "Mikronesia"},
  {"name": "Kenya"},
  {"name": "Sveits"},
  {"name": "Colombia"},
  {"name": "Panama"},
  {"name": "Saint Helena (Storbritannia)"},
  {"name": "Amerikas forente stater"},
  {"name": "Den demokratiske republikken Kongo"},
  {"name": "Marokko"},
  {"name": "Georgia"},
  {"name": "Qatar"},
  {"name": "Slovakia"},
  {"name": "Bangladesh"},
  {"name": "New Zealand"},
  {"name": "Montserrat (Storbritannia)"},
  {"name": "Eritrea"},
  {"name": "Ekvatorial-Guinea"},
  {"name": "Iran"},
  {"name": "Mauritius"},
  {"name": "Den dominikanske republikk"},
  {"name": "Bahrain"},
  {"name": "Slovenia"},
  {"name": "Lesotho"},
  {"name": "Portugal"},
  {"name": "Sør-Sudan"},
  {"name": "Zimbabwe"},
  {"name": "Venezuela"},
  {"name": "Slovakia"},
  {"name": "Caymanøyene (Storbritannia)"},
  {"name": "Øst-Timor"},
  {"name": "Spania"},
  {"name": "Sudan"},
  {"name": "Botswana"},
  {"name": "Falklandsøyene (Storbritannia)"},
  {"name": "Senegal"},
  {"name": "Hellas"},
  {"name": "Nicaragua"},
  {"name": "Canada"},
  {"name": "Syria"},
  {"name": "Paraguay"},
  {"name": "Libanon"},
  {"name": "Sør-Sudan"},
  {"name": "Storbritannia"},
  {"name": "Kiribati"},
  {"name": "Russland"},
  {"name": "Thailand"},
  {"name": "Togo"},
  {"name": "De britiske jomfruøyene (UK)"},
  {"name": "Namibia"},
  {"name": "Territorium"},
  {"name": "Oman"},
  {"name": "Tunisia"},
  {"name": "Turkmenistan"},
  {"name": "Guinea-Bissau"},
  {"name": "Bhutan"},
  {"name": "Åland (Finland)"},
  {"name": "Uganda"},
  {"name": "Honduras"},
  {"name": "Ungarn"},
  {"name": "Uruguay"},
  {"name": "Pakistan"},
  {"name": "Salomonøyene"},
  {"name": "Vatikanstaten"},
  {"name": "Indonesia"},
  {"name": "Vietnam"},
  {"name": "Tsjekkia"},
  {"name": "Tyskland"},
  {"name": "Serbia"},
  {"name": "Seychellene"},
  {"name": "Ecuador"},
  {"name": "Saint Vincent og Grenadinene"},
  {"name": "Amerikansk Samoa"},
  {"name": "Makedonia"},
  {"name": "Ukraina"},
  {"name": "Aruba (Nederland)"},
  {"name": "Ascension (Storbritannia)"},
  {"name": "Tristan da Cunha (UK)"},
  {"name": "Guinea"},
  {"name": "Caymanøyene (Storbritannia)"},
  {"name": "Australia"},
  {"name": "Saudi-Arabia"},
  {"name": "Surinam"},
  {"name": "England (Storbritannia)"},
  {"name": "Falklandsøyene (Storbritannia)"},
  {"name": "Fransk Polynesia (Frankrike)"},
  {"name": "De franske sørterritorier (Frankrike)"},
  {"name": "Færøyene (Danmark)"},
  {"name": "Finland"},
  {"name": "El Salvador"},
  {"name": "Guam"},
  {"name": "Guernsey (Storbritannia)"},
  {"name": "Isle of Man (Storbritannia)"},
  {"name": "Romania"},
  {"name": "Kokosøyene (Australia)"},
  {"name": "Mayotte (Frankrike)"},
  {"name": "Malaysia"},
  {"name": "Hovedsteder i biland"},
  {"name": "Nord-Marianene"},
  {"name": "Norfolkøya (Australia)"},
  {"name": "Taiwan"},
  {"name": "Pitcairnøyene (Storbritannia)"},
  {"name": "Puerto Rico"},
  {"name": "Saint-Barthélemy (Frankrike)"},
  {"name": "Mexico"},
  {"name": "Saint-Martin (Frankrike)"},
  {"name": "Afghanistan"},
  {"name": "Japan"},
  {"name": "Moldova"},
  {"name": "Tristan da Cunha (UK)"},
  {"name": "Kapp Verde"},
  {"name": "Wallis- og Futunaøyene (Frankrike)"},
  {"name": "Åland (Finland)"}
];