// App
export const APP_INIT = 'APP/INIT';
export const APP_INIT_COMPLETE = 'APP/INIT/COMPLETE';

// Dialog
export const OPEN_DIALOG  = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';

// Authentication
export const AUTHENTICATION_SEND_CREDENTIALS = 'AUTHENTICATION/SEND/CREDENTIALS';
export const AUTHENTICATION_CREDENTIALS_VALID = 'AUTHENTICATION/CREDENTIALS/VALID';
export const AUTHENTICATION_CREDENTIALS_INVALID = 'AUTHENTICATION/CREDENTIALS/INVALID';
export const AUTHENTICATION_USER    = 'AUTHENTICATION/USER';
export const AUTHENTICATION_LOADING = 'AUTHENTICATION/LOADING';
export const AUTHENTICATION_LOG_OUT = 'AUTHENTICATION/LOG_OUT';